/**
 * Copyright 2015 Huawei Technologies Co., Ltd. All rights reserved.
 * eSDK is licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   
 * http://www.apache.org/licenses/LICENSE-2.0
 *   
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.huawei.esdk.ivs.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.huawei.esdk.ivs.professional.local.bean.DeviceBriefInfos;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2014-01-06T23:40:36.102+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "esdk_ivs_professional_server", name = "IVSProfessional.ClusterManager")
@XmlSeeAlso({ObjectFactory.class})
public interface IVSProfessionalClusterManager {

    @RequestWrapper(localName = "getNVRList", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetNVRList")
    @WebMethod(action = "esdk_ivs_professional_server.getNVRList")
    @ResponseWrapper(localName = "getNVRListResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetNVRListResponse")
    public void getNVRList(
        @WebParam(name = "domainCode", targetNamespace = "")
        java.lang.String domainCode,
        @WebParam(name = "serverType", targetNamespace = "")
        java.lang.Integer serverType,
        @WebParam(name = "indexRange", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.IndexRange indexRange,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "nvrInfos", targetNamespace = "")
        javax.xml.ws.Holder<DeviceBriefInfos> nvrInfos
    );
}
