/**
 * Copyright 2015 Huawei Technologies Co., Ltd. All rights reserved.
 * eSDK is licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   
 * http://www.apache.org/licenses/LICENSE-2.0
 *   
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.huawei.esdk.ivs.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.huawei.esdk.ivs.professional.local.bean.RecordInfos;
import com.huawei.esdk.ivs.professional.local.bean.RecordPlan;
import com.huawei.esdk.ivs.professional.local.bean.ResultInfos;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2014-01-06T23:40:36.108+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "esdk_ivs_professional_server", name = "IVSProfessional.RecordManager")
@XmlSeeAlso({ObjectFactory.class})
public interface IVSProfessionalRecordManager {

    @RequestWrapper(localName = "queryRecordList", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.QueryRecordList")
    @WebMethod(action = "esdk_ivs_professional_server.queryRecordList")
    @ResponseWrapper(localName = "queryRecordListResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.QueryRecordListResponse")
    public void queryRecordList(
        @WebParam(name = "queryFormat", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.QueryUnifiedFormat queryFormat,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "recordInfos", targetNamespace = "")
        javax.xml.ws.Holder<RecordInfos> recordInfos
    );

    @RequestWrapper(localName = "getRecordPlan", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetRecordPlan")
    @WebMethod(action = "esdk_ivs_professional_server.getRecordPlan")
    @ResponseWrapper(localName = "getRecordPlanResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetRecordPlanResponse")
    public void getRecordPlan(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "recordMethod", targetNamespace = "")
        java.lang.Integer recordMethod,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "recordPlan", targetNamespace = "")
        javax.xml.ws.Holder<RecordPlan> recordPlan
    );

    @RequestWrapper(localName = "getRecordList", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetRecordList")
    @WebMethod(action = "esdk_ivs_professional_server.getRecordList")
    @ResponseWrapper(localName = "getRecordListResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetRecordListResponse")
    public void getRecordList(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "recordMethod", targetNamespace = "")
        java.lang.Integer recordMethod,
        @WebParam(name = "timeSpan", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.TimeSpan timeSpan,
        @WebParam(name = "indexRange", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.IndexRange indexRange,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "recordInfos", targetNamespace = "")
        javax.xml.ws.Holder<RecordInfos> recordInfos
    );

    @RequestWrapper(localName = "deleteRecordPlan", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.DeleteRecordPlan")
    @WebMethod(action = "esdk_ivs_professional_server.deleteRecordPlan")
    @ResponseWrapper(localName = "deleteRecordPlanResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.DeleteRecordPlanResponse")
    public void deleteRecordPlan(
        @WebParam(name = "deviceNum", targetNamespace = "")
        java.lang.Integer deviceNum,
        @WebParam(name = "deviceCodeList", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.DeviceCodeList deviceCodeList,
        @WebParam(name = "recordMethod", targetNamespace = "")
        java.lang.Integer recordMethod,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultInfos", targetNamespace = "")
        javax.xml.ws.Holder<ResultInfos> resultInfos
    );

    @RequestWrapper(localName = "modifyRecordPlan", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.ModifyRecordPlan")
    @WebMethod(action = "esdk_ivs_professional_server.modifyRecordPlan")
    @ResponseWrapper(localName = "modifyRecordPlanResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.ModifyRecordPlanResponse")
    public void modifyRecordPlan(
        @WebParam(name = "deviceNum", targetNamespace = "")
        java.lang.Integer deviceNum,
        @WebParam(name = "deviceCodeList", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.DeviceCodeList deviceCodeList,
        @WebParam(name = "recordPlan", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.RecordPlan recordPlan,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultInfos", targetNamespace = "")
        javax.xml.ws.Holder<ResultInfos> resultInfos
    );

    @RequestWrapper(localName = "addRecordPlan", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.AddRecordPlan")
    @WebMethod(action = "esdk_ivs_professional_server.addRecordPlan")
    @ResponseWrapper(localName = "addRecordPlanResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.AddRecordPlanResponse")
    public void addRecordPlan(
        @WebParam(name = "deviceNum", targetNamespace = "")
        java.lang.Integer deviceNum,
        @WebParam(name = "deviceCodeList", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.DeviceCodeList deviceCodeList,
        @WebParam(name = "recordPlan", targetNamespace = "")
        com.huawei.esdk.ivs.professional.local.bean.RecordPlan recordPlan,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultInfos", targetNamespace = "")
        javax.xml.ws.Holder<ResultInfos> resultInfos
    );
}
