/**
 * Copyright 2015 Huawei Technologies Co., Ltd. All rights reserved.
 * eSDK is licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   
 * http://www.apache.org/licenses/LICENSE-2.0
 *   
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.huawei.esdk.ivs.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 2.6.10
 * 2014-01-06T23:40:35.994+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "esdk_ivs_professional_server", name = "IVSProfessional.Common")
@XmlSeeAlso({ObjectFactory.class})
public interface IVSProfessionalCommon {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "registerNotification", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.RegisterNotification")
    @WebMethod(action = "esdk_ivs_professional_server.registerNotification")
    @ResponseWrapper(localName = "registerNotificationResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.RegisterNotificationResponse")
    public java.lang.Integer registerNotification(
        @WebParam(name = "wsUri", targetNamespace = "")
        java.lang.String wsUri
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "keepAlive", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.KeepAlive")
    @WebMethod(action = "esdk_ivs_professional_server.keepAlive")
    @ResponseWrapper(localName = "keepAliveResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.KeepAliveResponse")
    public java.lang.Integer keepAlive();

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.Login")
    @WebMethod(action = "esdk_ivs_professional_server.login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.LoginResponse")
    public java.lang.Integer login(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @RequestWrapper(localName = "getVersion", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetVersion")
    @WebMethod(action = "esdk_ivs_professional_server.getVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetVersionResponse")
    public void getVersion(
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "version", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> version
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.Logout")
    @WebMethod(action = "esdk_ivs_professional_server.logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.LogoutResponse")
    public java.lang.Integer logout();
}
