/**
 * Copyright 2015 Huawei Technologies Co., Ltd. All rights reserved.
 * eSDK is licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   
 * http://www.apache.org/licenses/LICENSE-2.0
 *   
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.huawei.esdk.ivs.test.service.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.esdk.ivs.test.bean.MediaAddress;
import com.huawei.esdk.ivs.test.bean.OperationLogInfos;
import com.huawei.esdk.ivs.test.bean.PTZControlInfo;
import com.huawei.esdk.ivs.test.bean.PTZPresetInfo;
import com.huawei.esdk.ivs.test.bean.PTZPresetInfoList;
import com.huawei.esdk.ivs.test.bean.PlaybackParam;
import com.huawei.esdk.ivs.test.bean.QueryUnifiedFormat;
import com.huawei.esdk.ivs.test.bean.RealplayParam;


/**
 * This class was generated by Apache CXF 2.6.10
 * 2014-01-06T23:40:36.047+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "esdk_ivs_professional_server", name = "IVSProfessional.BusinessManager")
@XmlSeeAlso({ObjectFactory.class})
public interface IVSProfessionalBusinessManager {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "stopPlatformRecord", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.StopPlatformRecord")
    @WebMethod(action = "esdk_ivs_professional_server.stopPlatformRecord")
    @ResponseWrapper(localName = "stopPlatformRecordResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.StopPlatformRecordResponse")
    public java.lang.Integer stopPlatformRecord(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode
    );

    @RequestWrapper(localName = "startRealPlayByIPEx", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.bean.StartRealPlayByIPEx")
    @WebMethod(action = "esdk_ivs_professional_server.startRealPlayByIPEx")
    @ResponseWrapper(localName = "startRealPlayByIPExResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.bean.StartRealPlayByIPExResponse")
    public void startRealPlayByIPEx(
        @WebParam(name = "realplayParam", targetNamespace = "")
        RealplayParam realplayParam,
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "mediaAddrDst", targetNamespace = "")
        MediaAddress mediaAddrDst,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "mediaAddrSrc", targetNamespace = "")
        javax.xml.ws.Holder<MediaAddress> mediaAddrSrc,
        @WebParam(mode = WebParam.Mode.OUT, name = "handle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Long> handle
    );

    @RequestWrapper(localName = "addPTZPreset", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.AddPTZPreset")
    @WebMethod(action = "esdk_ivs_professional_server.addPTZPreset")
    @ResponseWrapper(localName = "addPTZPresetResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.AddPTZPresetResponse")
    public void addPTZPreset(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "presetName", targetNamespace = "")
        java.lang.String presetName,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "presetIndex", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> presetIndex
    );

    @RequestWrapper(localName = "startPlatformPlayBackByIP", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.bean.StartPlatformPlayBackByIP")
    @WebMethod(action = "esdk_ivs_professional_server.startPlatformPlayBackByIP")
    @ResponseWrapper(localName = "startPlatformPlayBackByIPResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.bean.StartPlatformPlayBackByIPResponse")
    public void startPlatformPlayBackByIP(
        @WebParam(name = "playbackParam", targetNamespace = "")
        PlaybackParam playbackParam,
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "mediaAddrDst", targetNamespace = "")
        MediaAddress mediaAddrDst,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "mediaAddrSrc", targetNamespace = "")
        javax.xml.ws.Holder<MediaAddress> mediaAddrSrc,
        @WebParam(mode = WebParam.Mode.OUT, name = "handle", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Long> handle
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "stopRealPlayByIPEx", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.StopRealPlayByIPEx")
    @WebMethod(action = "esdk_ivs_professional_server.stopRealPlayByIPEx")
    @ResponseWrapper(localName = "stopRealPlayByIPExResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.StopRealPlayByIPExResponse")
    public java.lang.Integer stopRealPlayByIPEx(
        @WebParam(name = "handle", targetNamespace = "")
        long handle
    );

    @RequestWrapper(localName = "getPTZPresetList", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.bean.GetPTZPresetList")
    @WebMethod(action = "esdk_ivs_professional_server.getPTZPresetList")
    @ResponseWrapper(localName = "getPTZPresetListResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.bean.GetPTZPresetListResponse")
    public void getPTZPresetList(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "ptzPresetInfoList", targetNamespace = "")
        javax.xml.ws.Holder<PTZPresetInfoList> ptzPresetInfoList,
        @WebParam(mode = WebParam.Mode.OUT, name = "ptzPresetNum", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> ptzPresetNum
    );

    @RequestWrapper(localName = "ptzControl", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.PtzControl")
    @WebMethod(action = "esdk_ivs_professional_server.ptzControl")
    @ResponseWrapper(localName = "ptzControlResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.PtzControlResponse")
    public void ptzControl(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "controlCode", targetNamespace = "")
        java.lang.Integer controlCode,
        @WebParam(name = "controlPara1", targetNamespace = "")
        java.lang.String controlPara1,
        @WebParam(name = "controlPara2", targetNamespace = "")
        java.lang.String controlPara2,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "lockStatus", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> lockStatus
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "stopPlatformPlayBackByIP", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.StopPlatformPlayBackByIP")
    @WebMethod(action = "esdk_ivs_professional_server.stopPlatformPlayBackByIP")
    @ResponseWrapper(localName = "stopPlatformPlayBackByIPResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.StopPlatformPlayBackByIPResponse")
    public java.lang.Integer stopPlatformPlayBackByIP(
        @WebParam(name = "handle", targetNamespace = "")
        long handle
    );

    @RequestWrapper(localName = "ptzControlWithLockerInfo", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.PtzControlWithLockerInfo")
    @WebMethod(action = "esdk_ivs_professional_server.ptzControlWithLockerInfo")
    @ResponseWrapper(localName = "ptzControlWithLockerInfoResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.PtzControlWithLockerInfoResponse")
    public void ptzControlWithLockerInfo(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "controlCode", targetNamespace = "")
        java.lang.Integer controlCode,
        @WebParam(name = "controlPara1", targetNamespace = "")
        java.lang.String controlPara1,
        @WebParam(name = "controlPara2", targetNamespace = "")
        java.lang.String controlPara2,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "ptzControlInfo", targetNamespace = "")
        javax.xml.ws.Holder<PTZControlInfo> ptzControlInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "modifyPTZPreset", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.ModifyPTZPreset")
    @WebMethod(action = "esdk_ivs_professional_server.modifyPTZPreset")
    @ResponseWrapper(localName = "modifyPTZPresetResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.ModifyPTZPresetResponse")
    public java.lang.Integer modifyPTZPreset(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "ptzPresetInfo", targetNamespace = "")
        PTZPresetInfo ptzPresetInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "deletePTZPreset", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.DeletePTZPreset")
    @WebMethod(action = "esdk_ivs_professional_server.deletePTZPreset")
    @ResponseWrapper(localName = "deletePTZPresetResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.DeletePTZPresetResponse")
    public java.lang.Integer deletePTZPreset(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "presetIndex", targetNamespace = "")
        java.lang.Integer presetIndex
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "startPlatformRecord", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.StartPlatformRecord")
    @WebMethod(action = "esdk_ivs_professional_server.startPlatformRecord")
    @ResponseWrapper(localName = "startPlatformRecordResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.StartPlatformRecordResponse")
    public java.lang.Integer startPlatformRecord(
        @WebParam(name = "cameraCode", targetNamespace = "")
        java.lang.String cameraCode,
        @WebParam(name = "recordTime", targetNamespace = "")
        java.lang.Integer recordTime
    );
    
    @RequestWrapper(localName = "getOperationLog", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetOperationLog")
    @WebMethod(action = "esdk_ivs_professional_server.getOperationLog")
    @ResponseWrapper(localName = "getOperationLogResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetOperationLogResponse")
    public void getOperationLog(
        @WebParam(name = "unifiedQuery", targetNamespace = "")
        QueryUnifiedFormat unifiedQuery,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "operationLogInfos", targetNamespace = "")
        javax.xml.ws.Holder<OperationLogInfos> operationLogInfos
    );
    
    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "platformPlayBackPauseByIP", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.PlatformPlayBackPauseByIP")
    @WebMethod(action = "esdk_ivs_professional_server.platformPlayBackPauseByIP")
    @ResponseWrapper(localName = "platformPlayBackPauseByIPResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.PlatformPlayBackPauseByIPResponse")
    public int platformPlayBackPauseByIP(
        @WebParam(name = "playHandle", targetNamespace = "")
        long playHandle
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "platformPlayBackResumeByIP", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.PlatformPlayBackResumeByIP")
    @WebMethod(action = "esdk_ivs_professional_server.platformPlayBackResumeByIP")
    @ResponseWrapper(localName = "platformPlayBackResumeByIPResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.PlatformPlayBackResumeByIPResponse")
    public int platformPlayBackResumeByIP(
        @WebParam(name = "playHandle", targetNamespace = "")
        long playHandle
    );
    
    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "setPlayBackTimeByIP", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.SetPlayBackTimeByIP")
    @WebMethod(action = "esdk_ivs_professional_server.setPlayBackTimeByIP")
    @ResponseWrapper(localName = "setPlayBackTimeByIPResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.SetPlayBackTimeByIPResponse")
    public int setPlayBackTimeByIP(
        @WebParam(name = "playHandle", targetNamespace = "")
        long playHandle,
        @WebParam(name = "time", targetNamespace = "")
        int time
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "setPlayBackSpeedByIP", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.SetPlayBackSpeedByIP")
    @WebMethod(action = "esdk_ivs_professional_server.setPlayBackSpeedByIP")
    @ResponseWrapper(localName = "setPlayBackSpeedByIPResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.SetPlayBackSpeedByIPResponse")
    public int setPlayBackSpeedByIP(
        @WebParam(name = "playHandle", targetNamespace = "")
        long playHandle,
        @WebParam(name = "speed", targetNamespace = "")
        float speed
    );
}
