/**
 * Copyright 2015 Huawei Technologies Co., Ltd. All rights reserved.
 * eSDK is licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   
 * http://www.apache.org/licenses/LICENSE-2.0
 *   
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.huawei.esdk.ivs.test.service.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.esdk.ivs.test.bean.IndexRange;
import com.huawei.esdk.ivs.test.bean.QueryUnifiedFormat;
import com.huawei.esdk.ivs.test.bean.RoleInfos;
import com.huawei.esdk.ivs.test.bean.UserGroupInfos;
import com.huawei.esdk.ivs.test.bean.UserInfo;
import com.huawei.esdk.ivs.test.bean.UserInfos;


/**
 * This class was generated by Apache CXF 2.6.10
 * 2014-01-06T23:40:36.080+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "esdk_ivs_professional_server", name = "IVSProfessional.UserManager")
@XmlSeeAlso({ObjectFactory.class})
public interface IVSProfessionalUserManager {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "changePassword", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.ChangePassword")
    @WebMethod(action = "esdk_ivs_professional_server.changePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.ChangePasswordResponse")
    public java.lang.Integer changePassword(
        @WebParam(name = "oldPassword", targetNamespace = "")
        java.lang.String oldPassword,
        @WebParam(name = "newPassword", targetNamespace = "")
        java.lang.String newPassword
    );

    @RequestWrapper(localName = "getUserId", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetUserId")
    @WebMethod(action = "esdk_ivs_professional_server.getUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetUserIdResponse")
    public void getUserId(
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "userId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> userId
    );

    @RequestWrapper(localName = "getUserInfo", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetUserInfo")
    @WebMethod(action = "esdk_ivs_professional_server.getUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetUserInfoResponse")
    public void getUserInfo(
        @WebParam(name = "domainCode", targetNamespace = "")
        java.lang.String domainCode,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Integer userId,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "userInfo", targetNamespace = "")
        javax.xml.ws.Holder<UserInfo> userInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.DeleteUser")
    @WebMethod(action = "esdk_ivs_professional_server.deleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.DeleteUserResponse")
    public java.lang.Integer deleteUser(
        @WebParam(name = "domainCode", targetNamespace = "")
        java.lang.String domainCode,
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Integer userId
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "modifyUser", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.ModifyUser")
    @WebMethod(action = "esdk_ivs_professional_server.modifyUser")
    @ResponseWrapper(localName = "modifyUserResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.ModifyUserResponse")
    public java.lang.Integer modifyUser(
        @WebParam(name = "userInfo", targetNamespace = "")
        UserInfo userInfo
    );

    @RequestWrapper(localName = "getUserList", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetUserList")
    @WebMethod(action = "esdk_ivs_professional_server.getUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetUserListResponse")
    public void getUserList(
        @WebParam(name = "domainCode", targetNamespace = "")
        java.lang.String domainCode,
        @WebParam(name = "unifiedQuery", targetNamespace = "")
        QueryUnifiedFormat unifiedQuery,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "userInfos", targetNamespace = "")
        javax.xml.ws.Holder<UserInfos> userInfos
    );

    @RequestWrapper(localName = "addUser", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.AddUser")
    @WebMethod(action = "esdk_ivs_professional_server.addUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.AddUserResponse")
    public void addUser(
        @WebParam(name = "userInfo", targetNamespace = "")
        UserInfo userInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "userId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> userId
    );
    
    @RequestWrapper(localName = "getUserGroupList", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetUserGroupList")
    @WebMethod(action = "esdk_ivs_professional_server.getUserGroupList")
    @ResponseWrapper(localName = "getUserGroupListResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetUserGroupListResponse")
    public void getUserGroupList(
        @WebParam(name = "domainCode", targetNamespace = "")
        java.lang.String domainCode,
        @WebParam(name = "indexRange", targetNamespace = "")
        IndexRange indexRange,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "userGroupInfos", targetNamespace = "")
        javax.xml.ws.Holder<UserGroupInfos> userGroupInfos
    );

    @RequestWrapper(localName = "getRoleList", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetRoleList")
    @WebMethod(action = "esdk_ivs_professional_server.getRoleList")
    @ResponseWrapper(localName = "getRoleListResponse", targetNamespace = "esdk_ivs_professional_server", className = "com.huawei.esdk.ivs.professional.local.impl.autogen.GetRoleListResponse")
    public void getRoleList(
        @WebParam(name = "domainCode", targetNamespace = "")
        java.lang.String domainCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "roleInfos", targetNamespace = "")
        javax.xml.ws.Holder<RoleInfos> roleInfos
    );
}
