/**
 * Copyright 2015 Huawei Technologies Co., Ltd. All rights reserved.
 * eSDK is licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   
 * http://www.apache.org/licenses/LICENSE-2.0
 *   
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.huawei.esdk.platform.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2014-10-17T16:40:08.918+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "esdk_platform", name = "Platform.KeyMgr")
@XmlSeeAlso({ObjectFactory.class})
public interface PlatformKeyMgr {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "setSecretKey", targetNamespace = "esdk_platform", className = "com.huawei.esdk.platform.professional.local.impl.autogen.SetSecretKey")
    @WebMethod(action = "esdk_platformsetSecretKey")
    @ResponseWrapper(localName = "setSecretKeyResponse", targetNamespace = "esdk_platform", className = "com.huawei.esdk.platform.professional.local.impl.autogen.SetSecretKeyResponse")
    public int setSecretKey(
        @WebParam(name = "secretType", targetNamespace = "")
        java.lang.String secretType,
        @WebParam(name = "secretKey", targetNamespace = "")
        java.lang.String secretKey,
        @WebParam(name = "iv", targetNamespace = "")
        java.lang.String iv
    );

    @RequestWrapper(localName = "getPublicKey", targetNamespace = "esdk_platform", className = "com.huawei.esdk.platform.professional.local.impl.autogen.GetPublicKey")
    @WebMethod(action = "esdk_platformgetPublicKey")
    @ResponseWrapper(localName = "getPublicKeyResponse", targetNamespace = "esdk_platform", className = "com.huawei.esdk.platform.professional.local.impl.autogen.GetPublicKeyResponse")
    public void getPublicKey(
        @WebParam(name = "secretType", targetNamespace = "")
        java.lang.String secretType,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "publicKey", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> publicKey
    );
}
